name: Create Release

on:
  push:
    branches: [main] 

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
#       - name: Set tag env
#         run: echo ::set-env name=tag::${GITHUB_REF:11}
#         id: set_tag_env
        
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
#           RELEASE_VERSION: ${{ steps.set_tag_env.outputs.tag }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
